### ISSUE TITLE
Accessing 2nd page clears search criteria

### ISSUE THREAD

**Issue by neuropet** [nih-fmrif/golden_project#2]
Searching for scanner FMRIFD7T, first page of results looks fine but when next page is examined, search criteria get reset to null and results get scrambled.

(Uh oh - I hit the download button on series without thinking (too excited I guess). Froze for a while)

**Comment by neuropet** [comment]
This seems to be a general problem (true also for investigator and other fields).

**Comment by jvarada** [comment]
Fixed.
