### ISSUE TITLE
searching with multi echo alone causes traceback

### ISSUE THREAD

**Issue by neuropet** [nih-fmrif/golden_project#3]
just checking multi echo and searching causes system to crash

Request Method: | POST
-- | --
http://localhost:8888/gold/
2.0.2
OperationalError
SELECTs to the left and right of UNION do not have the same number of result columns
/home/varadajc/anaconda3/envs/golden/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 303
/home/varadajc/anaconda3/envs/golden/bin/python
3.6.4
['/bromineData/golden_project',  '/home/varadajc/anaconda3/envs/golden/lib/python36.zip',  '/home/varadajc/anaconda3/envs/golden/lib/python3.6',  '/home/varadajc/anaconda3/envs/golden/lib/python3.6/lib-dynload',  '/home/varadajc/anaconda3/envs/golden/lib/python3.6/site-packages']
Wed, 14 Feb 2018 17:10:46 +0000

**Comment by jvarada** [comment]
Fixed.
